#!/usr/bin/env python3
"""
Keys for the Sarus parameter lock (libraries/AP_SarusLock).

The private key is never stored. It is derived from the admin password:

    seed = scrypt(NFC(password) as UTF-8, salt, N=65536, r=8, p=1, 32 bytes)
    Ed25519 private key = seed; the public key follows from it

Sarus Operation Planner derives the same key when someone types the password, and the
aircraft checks its signature against the public keys compiled into the firmware.

  lock_keys.py header [keys.json]   write AP_SarusLock_keys.h from the key list
  lock_keys.py setup [keys.json]    ask for a new admin password and add its public key
  lock_keys.py test                 check the derivation against the simulator test key

Salts and public keys are not secret. The password is, and it is only ever typed here.
"""
import datetime
import getpass
import hashlib
import json
import os
import sys
import unicodedata

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
DEFAULT_JSON = os.path.join(HERE, 'sarus-lock-keys.json')
HEADER = os.path.join(ROOT, 'libraries', 'AP_SarusLock', 'AP_SarusLock_keys.h')

KDF = {'name': 'scrypt', 'n': 65536, 'r': 8, 'p': 1}

# simulator builds only (waf configure --define=AP_SARUS_LOCK_TEST_KEY); this password is public
TEST_PASSWORD = 'sarus-sitl-test'
TEST_SALT = bytes.fromhex('53415255532d53494c2d544553542d31')  # "SARUS-SIL-TEST-1"


def derive_private(password, salt):
    pw = unicodedata.normalize('NFC', password).encode('utf-8')
    seed = hashlib.scrypt(pw, salt=salt, n=KDF['n'], r=KDF['r'], p=KDF['p'],
                          maxmem=256 * 1024 * 1024, dklen=32)
    return Ed25519PrivateKey.from_private_bytes(seed)


def public_bytes(private):
    return private.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)


def c_bytes(b):
    return '{' + ','.join('0x%02x' % x for x in b) + '}'


def load(path):
    if not os.path.exists(path):
        return {'version': 1, 'kdf': KDF, 'keys': []}
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    if data.get('kdf') != KDF:
        raise SystemExit('unsupported key derivation in %s' % path)
    return data


def write_header(path):
    data = load(path)
    keys = [k for k in data['keys'] if k.get('public')]
    test_pub = public_bytes(derive_private(TEST_PASSWORD, TEST_SALT))
    lines = [
        '// Public keys for the Sarus parameter lock. Generated by Tools/sarus/lock_keys.py',
        '// from Tools/sarus/sarus-lock-keys.json; edit that file and rerun, not this one.',
        '// Public keys are safe to publish. The matching private keys come from the admin',
        '// password and exist only in Sarus Operation Planner while it is unlocked.',
        '#pragma once',
        '',
        '// simulator test key, compiled in only with --define=AP_SARUS_LOCK_TEST_KEY',
        '#define AP_SARUS_LOCK_TEST_KEY_BYTES %s' % c_bytes(test_pub),
        '',
        '#define AP_SARUS_LOCK_OWNER_KEY_COUNT %d' % len(keys),
    ]
    if keys:
        lines.append('#define AP_SARUS_LOCK_OWNER_KEYS \\')
        for k in keys:
            lines.append('    { %s }, /* %s */ \\' % (c_bytes(bytes.fromhex(k['public'])), k['id']))
        lines.append('')
    else:
        lines.append('#define AP_SARUS_LOCK_OWNER_KEYS')
    with open(HEADER, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote %s with %d owner key(s)' % (HEADER, len(keys)))


def setup(path):
    data = load(path)
    print('Choose the Sarus admin password. It unlocks parameter changes in every copy of')
    print('Sarus Operation Planner and on every aircraft running Sarus firmware built after')
    print('this. Use at least 12 characters. Nobody can recover it if it is lost.')
    while True:
        pw = getpass.getpass('Admin password: ')
        if len(pw) < 12:
            print('Too short; use at least 12 characters.')
            continue
        if getpass.getpass('Type it again: ') != pw:
            print('The two did not match.')
            continue
        break
    salt = os.urandom(16)
    pub = public_bytes(derive_private(pw, salt))
    del pw
    n = len(data['keys']) + 1
    key = {'id': 'owner-%d' % n, 'salt': salt.hex(), 'public': pub.hex(),
           'created': datetime.date.today().isoformat()}
    data['keys'].append(key)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, indent=2)
        f.write('\n')
    print('Added key %s to %s' % (key['id'], path))


def selftest():
    pub = public_bytes(derive_private(TEST_PASSWORD, TEST_SALT))
    print('test public key', pub.hex())
    # the password must decide the key, and the salt too
    assert public_bytes(derive_private(TEST_PASSWORD + 'x', TEST_SALT)) != pub
    assert public_bytes(derive_private(TEST_PASSWORD, bytes(16))) != pub
    # NFC: a precomposed and a decomposed e-acute give the same key
    assert public_bytes(derive_private('café-sarus-test', TEST_SALT)) == \
        public_bytes(derive_private('café-sarus-test', TEST_SALT))
    print('ok')


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else ''
    path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_JSON
    if cmd == 'header':
        write_header(path)
    elif cmd == 'setup':
        setup(path)
        write_header(path)
    elif cmd == 'test':
        selftest()
    else:
        print(__doc__)
        sys.exit(1)
