// Public keys for the Sarus parameter lock. Generated by Tools/sarus/lock_keys.py
// from Tools/sarus/sarus-lock-keys.json; edit that file and rerun, not this one.
// Public keys are safe to publish. The matching private keys come from the admin
// password and exist only in Sarus Operation Planner while it is unlocked.
#pragma once

// simulator test key, compiled in only with --define=AP_SARUS_LOCK_TEST_KEY
#define AP_SARUS_LOCK_TEST_KEY_BYTES {0xd1,0xf4,0x88,0xe0,0xce,0x6c,0xb0,0x97,0x2c,0x44,0xb8,0xed,0x72,0x31,0x78,0x78,0xaa,0x87,0x8e,0x8f,0x36,0x77,0xe1,0x7d,0x90,0x23,0xb3,0x25,0xc5,0xfe,0x9b,0x9b}

#define AP_SARUS_LOCK_OWNER_KEY_COUNT 0
#define AP_SARUS_LOCK_OWNER_KEYS
